### PR TITLE
Ensure ASCII citekeys for BibTeX entries

### LINKED ISSUE #96: GitHub: illegal bibtex key, non-ascii character
When creating a BibTeX citation for any of my software, GitHub will chose the BibTeX key to be `{lastname_title}`, in my case resulting in, e.g.,
```
Schlömer_pygmsh_A_Python
```
This isn't a legal BibTeX key because of the `ö`, and should probably be replaced by `oe`.

### PR DESCRIPTION
**Pull request by hainesr**
This PR ensures that the citekey (formerly 'reference') for a BibTeX entry only has ASCII characters in it, as per the [spec](https://www.bibtex.com/g/bibtex-format/). It does not encode the citekey string in ASCII; it remains encoded as UTF-8. It only really handles Latin and Latin-like characters properly, but seeing as we're firmly in the realms of academic literature here - which is mostly in English - this is more than likely OK.

This code provides a simplified reimplementation of `parameterize` from `ActiveSupport::Inflector` backed up by a simplified reimplementation of `I18n.transliterate`. In #96 we talked about providing a best-effort solution to this issue by default, and using `ActiveSupport` when available, but really I think this implementation is so similar that this is no longer necessary. All that using `ActiveSupport` would give us extra is the ability to override certain localized transliterations, which, for the purposes of a auto-generated citekey, are almost certainly overkill. We certainly don't want to add `ActiveSupport` as a required dependency.

Fixes #96

### CODE REVIEW

**Review by arfon — APPROVED** [review]
⚡ Looks solid @hainesr!

**Comment by hainesr** [comment]
Ace, thanks @arfon!

**Comment by nschloe** [comment]
There is no special handling for `ö` as in `Schrödinger`. Is this implicit?

**Comment by hainesr** [comment]
`ö` is converted to `o`. I realise that `ö` has different conversions depending on the locale, including in some cases `oe`, but for the purposes of auto-generating a citekey, keeping the code as simple as possible, and not adding dependencies to the library, we can't take every transliteration into account, sorry.

**Comment by arfon** [comment]
@hainesr this PR and https://github.com/citation-file-format/ruby-cff/pull/95 are now live in production on GitHub.

**Pull request merged**
