### PR TITLE
Change DOI link to https

### PR DESCRIPTION
**Pull request by tmorrell**
It's recommended to use https for DOI links https://support.datacite.org/docs/datacite-doi-display-guidelines

### CODE REVIEW

**Comment by arfon** [comment]
👍 LGTM

**Comment by hainesr** [comment]
Hi @tmorrell, many thanks for this PR. Please could you update the test fixtures as well so the tests still pass?

**Comment by tmorrell** [comment]
@hainesr I think I got them all. Could you approve the test workflow to check?

**Comment by hainesr** [comment]
Thanks @tmorrell!

**Comment by paxos** [comment]
Thank you!

**Pull request merged**
