### PR TITLE
Validate CFF files

### LINKED ISSUE #6: Validate CITATION.cff files.
Can use [Kwalify](http://www.kuwata-lab.com/kwalify/ruby/users-guide.01.html)?

### PR DESCRIPTION
**Pull request by hainesr**
Comprehensive (I think!) support for validating CFF files against the `1.2.0` JSON Schema.

You can either use `validate!` to raise an error, or `validate` to return a result structure. Both mimic the underlying `JsonSchema` library validation output and provide full details of any validation failures detected.

Closes #6.

### CODE REVIEW

**Comment by hainesr** [comment]
Sorry @arfon - meant to tag you in this for a look.

Do you think this covers the functionality that people are after? And is it useable for GitHub? I noted your request for an error structure to be returned on validation failure.

**Comment by arfon** [comment]
😍 nice @hainesr! I've had a quick play around with the changes locally and things work pretty much as I'd expect/hope.

One quick thought – how do you think we should handle earlier versions of CFF? For example, if I use a file that has the `cff-version` set to `1.1.0` I get the following error:

```
"1.1.0 does not match /^1\\.2\\.0$/."
```

Which is correct I guess, but I'm wondering if we should return something a little more user friendly here such as 'validation only possible for cff-version >= `1.2.0`' or something like that?

**Comment by hainesr** [comment]
Hi @arfon, thanks for taking a look.

Yes I agree it would be nice to treat pre `1.2.0` CFF files in a more friendly way. I think it's quite hard to do in a way that is also consistent and compatible with any other validation failure. We could detect the `cff-version` prior to validation and raise a specific error? I think it still needs to be a `CFF::ValidationError` that's raised otherwise we make the workflow for library users complex, but it could have a nicer message. The difficulty comes with what to do about the result structure returned by the non-bang version of the `validate` method as that contains `JsonSchema` data structures that I'd rather not mess with if I can help it.

Another option - which I kind of like, but we'd need to document clearly - is that we could convert the older files to version `1.2.0` on load (which basically just means setting `cff-version` to `1.2.0` 😬) and then we can perform validation on all files. We should probably think a bit about the implications of this, but my gut feeling is that this would be OK for version `1.0` of the Ruby CFF gem to do. Thoughts?

**Comment by arfon** [comment]
> Another option - which I kind of like, but we'd need to document clearly - is that we could convert the older files to version 1.2.0 on load (which basically just means setting cff-version to 1.2.0 😬) and then we can perform validation on all files. We should probably think a bit about the implications of this, but my gut feeling is that this would be OK for version 1.0 of the Ruby CFF gem to do. Thoughts?

I _think_ this is OK? I mean, are versions < `v1.2.0` of CFF essentially a subset of CFF `v1.2.0`? If so, then doing this 'behind the scenes', i.e., setting `cff-version` to `1.2.0` is probably fine (and would allow us to make minimal changes here).

@sdruskat @jspaaks – any concerns with this approach?

**Comment by hainesr** [comment]
Part of my reasoning that it _should_ be OK, is that in the validation step we are validating the internal representation of the CFF file against the schema, rather than going through line-by-line of the file itself. So we've already converted whatever was in the file into internal (in this case) Ruby types anyway.

I tried it with the `complete.cff` file from the CFF version `1.0.3` examples:

```ruby
cff = CFF::File.read('test/files/complete.cff')
cff.validate! # => raises CFF::ValidationError (Validation error: #/cff-version: failed schema #/properties/cff-version: 1.0.3 does not match /^1\.2\.0$/.)
cff.cff_version = '1.2.0'
cff.validate! # => nil
```

So that gives me confidence that we wouldn't be breaking anything there. Of course this doesn't change the file on disk unless it is written explicitly.

**Comment by hainesr** [comment]
Interestingly I just found this quote from @sdruskat in https://github.com/citation-file-format/ruby-cff/issues/29#issuecomment-849540080

> In the format as is, nothing has been deprecated as of yet, so you could make a valid `1.0.3` file a valid `1.2.0` file by simply changing the value for `cff-version`.

**Comment by arfon** [comment]
> In the format as is, nothing has been deprecated as of yet, so you could make a valid 1.0.3 file a valid 1.2.0 file by simply changing the value for cff-version.

Perfect!

**Comment by hainesr** [comment]
Hi @arfon, I've implemented bumping the `cff-version` number now on this branch/PR. Please can you give it another whirl? And then hopefully we're good to go with validation!

**Comment by arfon** [comment]
:wave: @hainesr – apologies for not responding sooner here but I think I found a minor issue with these changes. Namely, that if there is no `cff-version` set in the file, the changes we've added to 'bump' all versions to >= v1.2.0 mean that we add a `cff-version` even if it's missing (which would be an invalid CFF file).

Steps to reproduce:


1. Remove the `cff-version` and `authors` block from the `CITATION.cff` file in this repository:

```
# This CITATION.cff file was created by ruby-cff (v 0.6.0).
# Gem: https://rubygems.org/gems/cff
# CFF: https://citation-file-format.github.io/

message: If you use ruby-cff in your work, please cite it using the following metadata
title: Ruby CFF Library
abstract: This library provides a Ruby interface to manipulate CITATION.cff files
keywords:
- ruby
- credit
- citation
- metadata
- cff
version: 0.6.0
doi: 10.5281/zenodo.1184077
date-released: 2018-07-29
license: Apache-2.0
repository-artifact: https://rubygems.org/gems/cff
repository-code: https://github.com/citation-file-format/ruby-cff

```

2. Load up the file: `cff = CFF::File.read('CITATION.cff')`
3. Validate:

```
irb(main):006:0> cff.validate
=> [false, [#<JsonSchema::ValidationError: #: failed schema #: "authors" wasn't supplied.>]]
irb(main):007:0> 
```

Result: The only error we have is on the authors field. Inspecting the CFF object shows that it has a `cff-version` (of 1.2.0) specified even though the file was missing this:

```
cff
=> #<CFF::File:0x00007ff8d45ed768 @filename="CITATION.cff", @model=#<CFF::Model:0x00007ff8d45ed6f0 @fields={"message"=>"If you use ruby-cff in your work, please cite it using the following metadata", "title"=>"Ruby CFF Library", "abstract"=>"This library provides a Ruby interface to manipulate CITATION.cff files", "keywords"=>["ruby", "credit", "citation", "metadata", "cff"], "version"=>"0.6.0", "doi"=>"10.5281/zenodo.1184077", "date-released"=>#<Date: 2018-07-29 ((2458329j,0s,0n),+0s,2299161j)>, "license"=>"Apache-2.0", "repository-artifact"=>"https://rubygems.org/gems/cff", "repository-code"=>"https://github.com/citation-file-format/ruby-cff", "cff-version"=>"1.2.0", "authors"=>[], "contact"=>[], "references"=>[]}>, @comment=["This CITATION.cff file was created by ruby-cff (v 0.6.0).", "Gem: https://rubygems.org/gems/cff", "CFF: https://citation-file-format.github.io/"], @dirty=false>
```

**Comment by hainesr** [comment]
Hmm... Yes I coded it to insert a `cff-version` even if there wasn't one. I think my reasoning was that if we're bumping from `1.0.3` to `1.2.0` anyway, then adding one if there isn't one would be OK - in the sense that we're trying to help people validate and `cff-version` is effectively just there to tell us what to validate against. If it still doesn't validate, then it is being caught, as above.

I hadn't thought about this case that you've shown here, but I think I'm comfortable with how it plays out. I am happy to change my mind though! Do you think this is a bug with the current implementation?

**Comment by arfon** [comment]
Ah OK. Well, I guess my point here is that I think we want people to author valid CFF files, and for a CFF file to be valid it must have a `cff-version` field. Currently `ruby-cff` will inform someone that their CFF file is valid, even if it's missing a required field which seems wrong to me?

**Comment by hainesr** [comment]
OK yes, when you put it like that 😄

I'll raise an issue as this has been merged now.

**Comment by hainesr** [comment]
For completeness, issue raised is #46.

**Pull request merged**
